
const MenuApi=[{
  id:0,
  image:"images/vegthali.jpg",
  category:"Lunch",
  name:"Veg Thali",
  color:"white",
  background:"black"
},{id:1,
  image:"images/sweet.jpg",
  category:"Lunch",
  name:"Sweet",
  color:"white",
  background:"black"
},{id:2,
  image:"images/allupakoida.jpg",
  category:"Snacks",
  name:"Allu Pakoda",color:"white",
  background:"black"},{id:3,
  image:"images/chola.jpg",
  category:"Snacks",
  name:"Chola chat",color:"white",
  background:"black"},{id:4,
  image:"images/corn.jpg",
  category:"Breakfast",
  name:"Corn",color:"white",
  background:"black"},{id:5,
  image:"images/maggi.jpg",
  category:"Breakfast",
  name:"Maggi",color:"white",
  background:"black"},{id:6,
  image:"images/momo.jpg",
  category:"Snacks",
  name:"Momo",color:"white",
  background:"black"},{id:7,
  image:"images/puri.jpg",
  category:"Breakfast",
  name:"Puri",color:"white",
  background:"black"},{id:8,
  image:"images/rajmarice.jpg",
  category:"Lunch",
  name:"Rajma Rice",color:"white",
  background:"black"}];
  export default MenuApi;